import dns from 'dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import mongoose from 'mongoose';
import Product from '../backend/models/Product.js';
const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '..', 'api', '.env') });

const products = [
  // ===== FACE (+4) =====
  {
    name: 'Compact Powder', brand: 'Lakme', category: 'face',
    description: 'Silky compact powder with a matte finish that sets makeup and controls shine. Enriched with talc and silica for a smooth, natural look.',
    ingredients: 'Talc, Silica, Dimethicone, Nylon-12, Zinc Stearate, Iron Oxides, Tocopheryl Acetate',
    howToUse: 'Apply with powder puff or brush all over face for a flawless finish.',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    variants: [{ label: 'Natural', price: 299, stock: 80 }, { label: 'Glow', price: 299, stock: 60 }],
    tags: ['compact', 'face', 'makeup', 'powder'],
    skinTypes: ['oily', 'combination'],
  },
  {
    name: 'CC Cream', brand: 'L\'Oreal Paris', category: 'face',
    description: 'Color-correcting cream with SPF 30 that evens out skin tone and provides light coverage. Infused with vitamin C for brightening.',
    ingredients: 'Aqua, Cyclopentasiloxane, Glycerin, Titanium Dioxide, Ascorbic Acid, Tocopherol',
    howToUse: 'Apply on clean, moisturized skin before sun exposure.',
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600'],
    variants: [{ label: 'Fair', price: 549, stock: 45 }, { label: 'Medium', price: 549, stock: 55 }, { label: 'Tan', price: 549, stock: 35 }],
    tags: ['cc cream', 'face', 'makeup', 'sunscreen'],
    skinTypes: ['all'],
  },
  {
    name: 'Bronzer Stick', brand: 'Sugar Cosmetics', category: 'face',
    description: 'Cream bronzer stick that gives a sun-kissed glow. Blendable formula that builds from a natural to a dramatic bronze.',
    ingredients: 'Caprylic/Capric Triglyceride, Candelilla Cera, Mica, Tocopheryl Acetate, Iron Oxides',
    howToUse: 'Apply to cheeks, forehead, and jawline then blend with fingertips.',
    images: ['https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=600'],
    variants: [{ label: 'Warm Bronze', price: 449, stock: 70 }, { label: 'Cool Bronze', price: 449, stock: 50 }],
    tags: ['bronzer', 'face', 'makeup', 'contour'],
    skinTypes: ['all'],
  },
  {
    name: 'Face Mist', brand: 'Plum', category: 'face',
    description: 'Refreshing face mist with rose water and aloe vera that hydrates, sets makeup, and revitalises tired skin throughout the day.',
    ingredients: 'Aqua, Rosa Damascena Flower Water, Aloe Barbadensis Leaf Juice, Glycerin, Tocopherol',
    howToUse: 'Hold 6 inches from face and mist generously before or after makeup.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: '50ml', price: 199, stock: 150 }, { label: '100ml', price: 299, stock: 100 }],
    tags: ['face mist', 'face', 'makeup', 'hydration'],
    skinTypes: ['all'],
  },

  // ===== LIPS (+6) =====
  {
    name: 'Liquid Lipstick', brand: 'Maybelline', category: 'lips',
    description: 'Long-lasting liquid lipstick with a matte finish that stays on for up to 16 hours. Lightweight and comfortable on the lips.',
    ingredients: 'Ricinus Communis Seed Oil, Dimethicone, Isododecane, Tocopheryl Acetate, Iron Oxides',
    howToUse: 'Apply evenly to clean lips and let dry for 30 seconds.',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    variants: [{ label: 'Red Velvet', price: 399, stock: 90 }, { label: 'Nude Dream', price: 399, stock: 85 }, { label: 'Plum Perfect', price: 399, stock: 70 }],
    tags: ['liquid lipstick', 'lips', 'makeup', 'matte'],
    skinTypes: ['all'],
  },
  {
    name: 'Lip Scrub', brand: 'Burt\'s Bees', category: 'lips',
    description: 'Gentle lip scrub with sugar crystals and coconut oil that exfoliates dead skin, leaving lips smooth and ready for color.',
    ingredients: 'Sucrose, Cocos Nucifera Oil, Ricinus Communis Seed Oil, Cera Alba, Tocopherol',
    howToUse: 'Massage a small amount onto lips, then rinse or wipe off.',
    images: ['https://images.unsplash.com/photo-1598803666444-9f56b5b296f8?w=600'],
    variants: [{ label: 'Brown Sugar', price: 199, stock: 130 }, { label: 'Mint', price: 199, stock: 110 }],
    tags: ['lip scrub', 'lips', 'exfoliator', 'natural'],
    skinTypes: ['all'],
  },
  {
    name: 'Lip Stain', brand: 'Wet n Wild', category: 'lips',
    description: 'Long-wearing lip stain that gives a just-bitten look. Lightweight, transfer-proof formula that lasts all day without touch-ups.',
    ingredients: 'Aqua, Propylene Glycol, Glycerin, Carmine, Tocopheryl Acetate',
    howToUse: 'Apply to clean lips and allow to dry for 30 seconds.',
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600'],
    variants: [{ label: 'Rose', price: 249, stock: 100 }, { label: 'Cherry', price: 249, stock: 90 }, { label: 'Berry', price: 249, stock: 80 }],
    tags: ['lip stain', 'lips', 'makeup', 'long-lasting'],
    skinTypes: ['all'],
  },
  {
    name: 'Plumping Lip Gloss', brand: 'NYX Professional', category: 'lips',
    description: 'High-shine lip gloss with a plumping effect. Infused with hyaluronic acid and peppermint oil for a tingling, volumizing sensation.',
    ingredients: 'Ricinus Communis Seed Oil, Caprylic/Capric Triglyceride, Simmondsia Chinensis Seed Oil, Tocopherol',
    howToUse: 'Apply directly to lips with wand applicator.',
    images: ['https://images.unsplash.com/photo-1598803666444-9f56b5b296f8?w=600'],
    variants: [{ label: 'Clear', price: 299, stock: 140 }, { label: 'Pink', price: 299, stock: 120 }],
    tags: ['lip gloss', 'lips', 'plump', 'shine'],
    skinTypes: ['all'],
  },
  {
    name: 'Lip Mask', brand: 'Laneige', category: 'lips',
    description: 'Overnight lip mask that deeply hydrates and repairs dry, chapped lips. Rich formula with berry extracts and vitamin C.',
    ingredients: 'Aqua, Glycerin, Caprylic/Capric Triglyceride, Butyrospermum Parkii Butter, Tocopherol',
    howToUse: 'Apply a generous layer to lips before bedtime. Rinse in the morning.',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    variants: [{ label: 'Berry', price: 399, stock: 75 }, { label: 'Vanilla', price: 399, stock: 65 }],
    tags: ['lip mask', 'lips', 'hydration', 'overnight'],
    skinTypes: ['all'],
  },
  {
    name: 'Lip Primer', brand: 'Sugar Cosmetics', category: 'lips',
    description: 'Smoothing lip primer that fills in fine lines and creates the perfect base for lip color. Extends the wear of lip products.',
    ingredients: 'Cyclopentasiloxane, Dimethicone, Silica, Tocopheryl Acetate',
    howToUse: 'Apply a thin layer to clean lips before lipstick or gloss.',
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600'],
    variants: [{ label: 'Universal', price: 199, stock: 90 }],
    tags: ['lip primer', 'lips', 'makeup', 'base'],
    skinTypes: ['all'],
  },

  // ===== EYES (+5) =====
  {
    name: 'Kajal Pencil', brand: 'Lakme', category: 'eyes',
    description: 'Ultra-black kajal pencil with a creamy, smudge-proof formula. Ophthalmologist-tested and safe for sensitive eyes.',
    ingredients: 'Isododecane, Cyclopentasiloxane, Polyethylene, Cera Alba, Carbon Black, Tocopherol',
    howToUse: 'Apply along the waterline and lash line for an intense smoky look.',
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600'],
    variants: [{ label: 'Black', price: 149, stock: 200 }, { label: 'Smokey Grey', price: 149, stock: 120 }],
    tags: ['kajal', 'eyes', 'makeup', 'eyeliner'],
    skinTypes: ['all'],
  },
  {
    name: 'False Lashes', brand: 'Wet n Wild', category: 'eyes',
    description: 'Natural-looking false eyelashes with a lightweight, flexible band. Reusable up to 10 times with proper care.',
    ingredients: 'Synthetic fibers, Polyester band',
    howToUse: 'Apply lash glue, wait 30 seconds, then press onto lash line.',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    variants: [{ label: 'Natural', price: 199, stock: 60 }, { label: 'Dramatic', price: 249, stock: 45 }],
    tags: ['lashes', 'eyes', 'makeup', 'false eyelashes'],
    skinTypes: ['all'],
  },
  {
    name: 'Eye Shadow Stick', brand: 'NYX Professional', category: 'eyes',
    description: 'Creamy eyeshadow stick that glides on effortlessly for a quick, one-sweep eye look. Blendable formula sets to a long-lasting finish.',
    ingredients: 'Cyclopentasiloxane, Dimethicone, Mica, Tocopheryl Acetate, Iron Oxides',
    howToUse: 'Draw directly onto eyelids and blend with finger or brush.',
    images: ['https://images.unsplash.com/photo-1631730359713-6b8f1c7bd7d2?w=600'],
    variants: [{ label: 'Champagne', price: 349, stock: 70 }, { label: 'Bronze', price: 349, stock: 60 }, { label: 'Rose Gold', price: 349, stock: 55 }],
    tags: ['eyeshadow stick', 'eyes', 'makeup', 'cream'],
    skinTypes: ['all'],
  },
  {
    name: 'Lash Growth Serum', brand: 'The Ordinary', category: 'eyes',
    description: 'Eyelash enhancing serum that promotes longer, thicker lashes in 4 weeks. Peptide-enriched formula safe for daily use.',
    ingredients: 'Aqua, Glycerin, Panthenol, Biotinoyl Tripeptide-1, Tocopherol',
    howToUse: 'Apply a thin line along upper lash line once daily.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    variants: [{ label: '3ml', price: 499, stock: 50 }],
    tags: ['lash serum', 'eyes', 'growth', 'treatment'],
    skinTypes: ['all'],
  },
  {
    name: 'Under Eye Brightener', brand: 'Maybelline', category: 'eyes',
    description: 'Light-reflecting concealer for the under-eye area that instantly brightens and depuffs. Infused with caffeine and vitamin C.',
    ingredients: 'Aqua, Glycerin, Caffeine, Ascorbic Acid, Dimethicone, Iron Oxides',
    howToUse: 'Dot under eyes and blend with ring finger or sponge.',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    variants: [{ label: 'Light', price: 399, stock: 80 }, { label: 'Medium', price: 399, stock: 70 }],
    tags: ['under eye', 'eyes', 'concealer', 'brightening'],
    skinTypes: ['all'],
  },

  // ===== SKIN (+4) =====
  {
    name: 'Retinol Night Cream', brand: 'Minimalist', category: 'skin',
    description: 'Anti-aging night cream with 0.3% pure retinol that reduces fine lines and improves skin texture over 8 weeks.',
    ingredients: 'Aqua, Retinol, Caprylic/Capric Triglyceride, Glycerin, Tocopherol, Panthenol',
    howToUse: 'Apply a pea-sized amount to clean skin at night. Start with twice weekly.',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600'],
    variants: [{ label: '30ml', price: 699, stock: 55 }, { label: '50ml', price: 999, stock: 30 }],
    tags: ['night cream', 'skin', 'retinol', 'anti-aging'],
    skinTypes: ['normal', 'dry'],
  },
  {
    name: 'Sheet Mask Pack', brand: 'Plum', category: 'skin',
    description: 'Pack of 5 rejuvenating sheet masks soaked in hyaluronic acid and aloe vera for intense hydration and glow.',
    ingredients: 'Aqua, Glycerin, Sodium Hyaluronate, Aloe Barbadensis Leaf Extract, Tocopherol',
    howToUse: 'Apply to clean face for 15-20 minutes, then pat remaining essence into skin.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: 'Hydration', price: 299, stock: 100 }, { label: 'Brightening', price: 299, stock: 90 }],
    tags: ['sheet mask', 'skin', 'hydration', 'treatment'],
    skinTypes: ['all'],
  },
  {
    name: 'Clay Face Mask', brand: 'Biotique', category: 'skin',
    description: 'Deep cleansing clay mask with bentonite clay and tea tree oil that draws out impurities and unclogs pores.',
    ingredients: 'Aqua, Bentonite, Kaolin, Glycerin, Melaleuca Alternifolia Leaf Oil, Tocopherol',
    howToUse: 'Apply a thick layer to clean face. Leave for 10 minutes, rinse with warm water.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    variants: [{ label: '50g', price: 249, stock: 80 }, { label: '100g', price: 399, stock: 50 }],
    tags: ['face mask', 'skin', 'clay', 'pores'],
    skinTypes: ['oily', 'combination'],
  },
  {
    name: 'Face Oil', brand: 'The Ordinary', category: 'skin',
    description: 'Nourishing face oil blend of squalane, rosehip, and jojoba that restores the skin barrier and adds a healthy glow.',
    ingredients: 'Squalane, Rosa Canina Seed Oil, Simmondsia Chinensis Seed Oil, Tocopherol',
    howToUse: 'Apply 2-3 drops to face after moisturizer, or mix into foundation.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    variants: [{ label: '30ml', price: 449, stock: 70 }],
    tags: ['face oil', 'skin', 'nourishment', 'glow'],
    skinTypes: ['dry', 'normal'],
  },

  // ===== HAIR (+7) =====
  {
    name: 'Dry Shampoo', brand: 'Biotique', category: 'hair',
    description: 'Refreshing dry shampoo that absorbs excess oil and adds volume between washes. Leaves no white residue.',
    ingredients: 'Oryza Sativa Starch, Zea Mays Starch, Silica, Parfum, Tocopherol',
    howToUse: 'Shake well, spray onto roots from 6 inches, massage in, and brush through.',
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600'],
    variants: [{ label: '150ml', price: 249, stock: 90 }],
    tags: ['dry shampoo', 'hair', 'volume', 'refresh'],
    skinTypes: ['all'],
  },
  {
    name: 'Hair Oil', brand: 'Moroccanoil', category: 'hair',
    description: 'Lightweight argan oil hair treatment that nourishes, strengthens, and adds shine without weighing hair down.',
    ingredients: 'Argania Spinosa Kernel Oil, Cyclomethicone, Dimethiconol, Tocopheryl Acetate',
    howToUse: 'Apply a small amount to damp or dry hair, focusing on ends.',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600'],
    variants: [{ label: '25ml', price: 399, stock: 80 }, { label: '50ml', price: 649, stock: 50 }],
    tags: ['hair oil', 'hair', 'argan oil', 'shine'],
    skinTypes: ['all'],
  },
  {
    name: 'Heat Protectant Spray', brand: 'L\'Oreal Paris', category: 'hair',
    description: 'Invisible heat protectant spray that shields hair from heat styling damage up to 230°C. Also reduces frizz and adds shine.',
    ingredients: 'Aqua, Dimethicone, VP/VA Copolymer, Hydrolyzed Keratin, Tocopherol',
    howToUse: 'Spray evenly on damp hair before blow-drying or heat styling.',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600'],
    variants: [{ label: '200ml', price: 349, stock: 70 }],
    tags: ['heat protectant', 'hair', 'styling', 'protection'],
    skinTypes: ['all'],
  },
  {
    name: 'Leave-In Conditioner', brand: 'Plum', category: 'hair',
    description: 'Lightweight leave-in conditioner that detangles, moisturizes, and protects hair. Enriched with aloe vera and vitamin E.',
    ingredients: 'Aqua, Cetearyl Alcohol, Aloe Barbadensis Leaf Juice, Glycerin, Tocopherol',
    howToUse: 'Apply to damp, towel-dried hair from mid-lengths to ends. Do not rinse.',
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600'],
    variants: [{ label: '150ml', price: 299, stock: 85 }],
    tags: ['leave-in conditioner', 'hair', 'moisture', 'detangle'],
    skinTypes: ['all'],
  },
  {
    name: 'Purple Shampoo', brand: 'Biotique', category: 'hair',
    description: 'Toning purple shampoo that neutralizes brassiness on blonde, silver, and highlighted hair for a cool-toned finish.',
    ingredients: 'Aqua, Cocamidopropyl Betaine, Decyl Glucoside, Violet Pigment, Tocopherol',
    howToUse: 'Use 1-2 times per week, leave on for 3-5 minutes, then rinse.',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600'],
    variants: [{ label: '200ml', price: 299, stock: 60 }, { label: '400ml', price: 449, stock: 35 }],
    tags: ['purple shampoo', 'hair', 'toner', 'blonde'],
    skinTypes: ['all'],
  },
  {
    name: 'Hair Brush', brand: 'Sugar Cosmetics', category: 'hair',
    description: 'Professional paddle hair brush with cushioned base that detangles gently and adds shine. Suitable for all hair types.',
    ingredients: 'Wooden handle, Cushioned rubber pad, Nylon bristles',
    howToUse: 'Brush through dry or damp hair starting from ends working up to roots.',
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600'],
    variants: [{ label: 'Large', price: 249, stock: 50 }, { label: 'Travel', price: 149, stock: 80 }],
    tags: ['hair brush', 'hair', 'tools', 'detangle'],
    skinTypes: ['all'],
  },
  {
    name: 'Sea Salt Spray', brand: 'L\'Oreal Paris', category: 'hair',
    description: 'Texturizing sea salt spray that creates effortless beachy waves and adds volume to limp hair.',
    ingredients: 'Aqua, Magnesium Sulfate, Maris Sal, Glycerin, Tocopherol',
    howToUse: 'Spray onto damp hair, scrunch, and air dry or diffuse for tousled waves.',
    images: ['https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600'],
    variants: [{ label: '150ml', price: 299, stock: 65 }],
    tags: ['sea salt spray', 'hair', 'waves', 'volume'],
    skinTypes: ['all'],
  },

  // ===== BODY (+7) =====
  {
    name: 'Body Wash', brand: 'Vaseline', category: 'body',
    description: 'Moisturizing body wash with cocoa butter and vitamin E that cleanses without stripping. Leaves skin soft and hydrated.',
    ingredients: 'Aqua, Glycerin, Cocamidopropyl Betaine, Theobroma Cacao Seed Butter, Tocopheryl Acetate',
    howToUse: 'Apply to wet skin, lather, and rinse thoroughly.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: '250ml', price: 149, stock: 200 }, { label: '500ml', price: 249, stock: 150 }],
    tags: ['body wash', 'body', 'cleanse', 'moisturizer'],
    skinTypes: ['all'],
  },
  {
    name: 'Hand Cream', brand: 'Burt\'s Bees', category: 'body',
    description: 'Intensive hand cream with shea butter and almond oil that repairs dry, cracked hands. Absorbs quickly without greasy residue.',
    ingredients: 'Aqua, Butyrospermum Parkii Butter, Prunus Amygdalus Dulcis Oil, Glycerin, Tocopherol',
    howToUse: 'Apply a small amount to hands as often as needed.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: '50ml', price: 199, stock: 120 }, { label: '100ml', price: 299, stock: 80 }],
    tags: ['hand cream', 'body', 'moisture', 'repair'],
    skinTypes: ['all'],
  },
  {
    name: 'Body Scrub Gloves', brand: 'Wet n Wild', category: 'body',
    description: 'Exfoliating body gloves that enhance your scrub routine. Remove dead skin and improve circulation for smoother, glowing skin.',
    ingredients: 'Nylon fibers, Polyester lining',
    howToUse: 'Wear gloves, apply body wash, and massage in circular motions over damp skin.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: 'Pair', price: 99, stock: 150 }],
    tags: ['body scrub', 'body', 'exfoliator', 'gloves'],
    skinTypes: ['all'],
  },
  {
    name: 'Body Butter', brand: 'Plum', category: 'body',
    description: 'Rich body butter with mango seed butter and coconut oil for deep, lasting hydration. Deliciously scented with vanilla and coconut.',
    ingredients: 'Aqua, Mangifera Indica Seed Butter, Cocos Nucifera Oil, Glycerin, Tocopherol',
    howToUse: 'Apply generously to body after shower, focusing on dry areas like elbows and knees.',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'],
    variants: [{ label: 'Vanilla', price: 349, stock: 70 }, { label: 'Coconut', price: 349, stock: 65 }],
    tags: ['body butter', 'body', 'moisturizer', 'rich'],
    skinTypes: ['dry', 'normal'],
  },
  {
    name: 'Foot Cream', brand: 'Mcaffeine', category: 'body',
    description: 'Revitalizing foot cream with peppermint and tea tree oil that soothes tired feet, softens calluses, and eliminates odor.',
    ingredients: 'Aqua, Glycerin, Mentha Piperita Oil, Melaleuca Alternifolia Leaf Oil, Camphor, Tocopherol',
    howToUse: 'Massage onto clean, dry feet focusing on heels and rough areas.',
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    variants: [{ label: '100ml', price: 199, stock: 70 }],
    tags: ['foot cream', 'body', 'foot care', 'soothing'],
    skinTypes: ['all'],
  },
  {
    name: 'Deodorant Spray', brand: 'Plum', category: 'body',
    description: 'Aluminum-free deodorant spray with natural essential oils that keeps you fresh for up to 24 hours.',
    ingredients: 'Alcohol Denat., Aqua, Parfum, Glycerin, Tocopherol',
    howToUse: 'Spray onto clean, dry underarms from a distance of 6 inches.',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'],
    variants: [{ label: 'Vanilla', price: 249, stock: 90 }, { label: 'Citrus', price: 249, stock: 85 }],
    tags: ['deodorant', 'body', 'fresh', 'natural'],
    skinTypes: ['all'],
  },
  {
    name: 'Massage Oil', brand: 'Biotique', category: 'body',
    description: 'Ayurvedic massage oil infused with sesame oil, almond oil, and ashwagandha. Nourishes muscles and promotes relaxation.',
    ingredients: 'Sesamum Indicum Seed Oil, Prunus Amygdalus Dulcis Oil, Withania Somnifera Extract, Tocopherol',
    howToUse: 'Warm oil in palms and massage onto body in circular motions.',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=600'],
    variants: [{ label: '200ml', price: 299, stock: 50 }],
    tags: ['massage oil', 'body', 'ayurvedic', 'relaxation'],
    skinTypes: ['all'],
  },

  // ===== TOOLS (+7) =====
  {
    name: 'Face Roller', brand: 'Sugar Cosmetics', category: 'tools',
    description: 'Jade face roller that reduces puffiness, improves circulation, and enhances product absorption. Dual-ended for face and eyes.',
    ingredients: 'Natural jade stone, Stainless steel frame',
    howToUse: 'Roll gently across face and neck in upward motions after applying serum.',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    variants: [{ label: 'Jade', price: 399, stock: 40 }, { label: 'Rose Quartz', price: 449, stock: 35 }],
    tags: ['face roller', 'tools', 'jade', 'massage'],
    skinTypes: ['all'],
  },
  {
    name: 'Brush Cleaning Mat', brand: 'Wet n Wild', category: 'tools',
    description: 'Silicone brush cleaning mat with multiple textured patterns for deep cleaning all types of makeup brushes.',
    ingredients: 'Food-grade silicone',
    howToUse: 'Wet brush, rub on mat with mild soap, rinse, and reshape bristles.',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    variants: [{ label: 'Pink', price: 199, stock: 60 }],
    tags: ['brush cleaner', 'tools', 'cleaning', 'silicone'],
    skinTypes: ['all'],
  },
  {
    name: 'Tweezer Set', brand: 'NYX Professional', category: 'tools',
    description: 'Precision tweezer set with slant, point, and flat tips for all brow grooming needs. Stainless steel with anti-slip grip.',
    ingredients: 'Stainless steel',
    howToUse: 'Grasp hair at the root and pull in the direction of growth.',
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600'],
    variants: [{ label: '3-Piece Set', price: 249, stock: 70 }],
    tags: ['tweezers', 'tools', 'brows', 'grooming'],
    skinTypes: ['all'],
  },
  {
    name: 'Mirror Vanity', brand: 'Sugar Cosmetics', category: 'tools',
    description: 'LED-lit vanity mirror with 10x magnification and adjustable brightness. USB rechargeable for perfect makeup application anywhere.',
    ingredients: 'ABS plastic, Glass mirror, LED lights, USB cable',
    howToUse: 'Place on flat surface and adjust brightness with touch sensor.',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    variants: [{ label: 'White', price: 799, stock: 25 }, { label: 'Rose Gold', price: 849, stock: 20 }],
    tags: ['mirror', 'tools', 'vanity', 'LED'],
    skinTypes: ['all'],
  },
  {
    name: 'Puff Set', brand: 'Wet n Wild', category: 'tools',
    description: 'Set of 3 ultra-soft velour powder puffs for setting makeup and applying powder. Washable and reusable.',
    ingredients: 'Velour microfiber',
    howToUse: 'Press powder into skin with rolling or pressing motion for an airbrushed finish.',
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    variants: [{ label: '3-Pack', price: 99, stock: 150 }],
    tags: ['puff', 'tools', 'powder', 'makeup'],
    skinTypes: ['all'],
  },
  {
    name: 'Hair Turban', brand: 'Plum', category: 'tools',
    description: 'Microfiber hair turban that quickly absorbs water from wet hair, reducing drying time and preventing frizz and breakage.',
    ingredients: 'Microfiber polyester',
    howToUse: 'Flip hair forward, place turban over head, twist, and secure with loop.',
    images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600'],
    variants: [{ label: 'Grey', price: 199, stock: 80 }, { label: 'Pink', price: 199, stock: 70 }],
    tags: ['hair turban', 'tools', 'hair care', 'microfiber'],
    skinTypes: ['all'],
  },
  {
    name: 'Brush Organizer', brand: 'Sugar Cosmetics', category: 'tools',
    description: 'Acrylic brush holder with compartments for keeping all your makeup brushes organized and within reach.',
    ingredients: 'Clear acrylic',
    howToUse: 'Place brushes in compartments and keep on vanity.',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    variants: [{ label: 'Small', price: 299, stock: 45 }, { label: 'Large', price: 449, stock: 30 }],
    tags: ['organizer', 'tools', 'storage', 'acrylic'],
    skinTypes: ['all'],
  },
];

const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI || process.env.MONGODB_URI);
  await Product.insertMany(products);
  const count = await Product.countDocuments();
  console.log(`${products.length} extra products seeded (total: ${count})`);
  await mongoose.disconnect();
};

seed().catch(e => { console.error(e); process.exit(1); });
